"""empty message

Revision ID: 7c0df77396c8
Revises: 
Create Date: 2022-11-14 18:09:53.761733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0df77396c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior',
    sa.Column('b_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('b_name', sa.String(length=64), nullable=True),
    sa.Column('b_status', sa.String(length=32), nullable=True),
    sa.Column('b_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('b_id'),
    sa.UniqueConstraint('b_name')
    )
    op.create_table('big_course',
    sa.Column('bc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bc_name', sa.String(length=32), nullable=True),
    sa.Column('bc_date', sa.String(length=32), nullable=True),
    sa.Column('bc_remark', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('bc_id')
    )
    op.create_table('small_course',
    sa.Column('sc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sc_name', sa.String(length=32), nullable=True),
    sa.Column('sc_group', sa.String(length=32), nullable=True),
    sa.Column('sc_start_time', sa.String(length=32), nullable=True),
    sa.Column('sc_end_time', sa.String(length=32), nullable=True),
    sa.Column('sc_room', sa.String(length=32), nullable=True),
    sa.Column('sc_date', sa.String(length=32), nullable=True),
    sa.Column('sc_remark', sa.String(length=128), nullable=True),
    sa.Column('sc_attendance_num', sa.Integer(), nullable=True),
    sa.Column('sc_member_num', sa.Integer(), nullable=True),
    sa.Column('sc_status', sa.Integer(), nullable=True),
    sa.Column('sc_big_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sc_big_course_id'], ['big_course.bc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sc_id')
    )
    op.create_table('classroom',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.String(length=32), nullable=True),
    sa.Column('c_date', sa.String(length=32), nullable=True),
    sa.Column('c_start_time', sa.String(length=32), nullable=True),
    sa.Column('c_end_time', sa.String(length=32), nullable=True),
    sa.Column('c_small_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_small_course_id'], ['small_course.sc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('c_id')
    )
    op.create_table('small_course_departments',
    sa.Column('scd_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scd_name', sa.String(length=32), nullable=True),
    sa.Column('scd_add_score', sa.Float(), nullable=True),
    sa.Column('scd_subtract_score', sa.Float(), nullable=True),
    sa.Column('scd_attendance_num', sa.Integer(), nullable=True),
    sa.Column('scd_small_course_id', sa.Integer(), nullable=True),
    sa.Column('scd_member_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scd_small_course_id'], ['small_course.sc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scd_id')
    )
    op.create_table('small_course_member',
    sa.Column('scm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scm_name', sa.String(length=32), nullable=True),
    sa.Column('scm_phone', sa.String(length=32), nullable=True),
    sa.Column('scm_course', sa.String(length=32), nullable=True),
    sa.Column('scm_seat_number', sa.String(length=32), nullable=True),
    sa.Column('scm_date', sa.String(length=32), nullable=True),
    sa.Column('scm_checkin_time', sa.DateTime(), nullable=True),
    sa.Column('scm_status', sa.Integer(), nullable=True),
    sa.Column('scm_score', sa.Float(), nullable=True),
    sa.Column('scm_group', sa.String(length=32), nullable=True),
    sa.Column('scm_firm_or_department', sa.String(length=128), nullable=True),
    sa.Column('scm_job', sa.String(length=32), nullable=True),
    sa.Column('scm_license_plate', sa.String(length=32), nullable=True),
    sa.Column('scm_destination', sa.String(length=32), nullable=True),
    sa.Column('scm_remark', sa.String(length=256), nullable=True),
    sa.Column('scm_add_score', sa.Float(), nullable=True),
    sa.Column('scm_subtract_score', sa.Float(), nullable=True),
    sa.Column('scm_behavior', sa.String(length=128), nullable=True),
    sa.Column('scm_small_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scm_small_course_id'], ['small_course.sc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scm_id')
    )
    op.create_table('member_behaviors',
    sa.Column('mb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mb_member_id', sa.Integer(), nullable=True),
    sa.Column('mb_behavior_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mb_behavior_id'], ['behavior.b_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mb_member_id'], ['small_course_member.scm_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mb_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_behaviors')
    op.drop_table('small_course_member')
    op.drop_table('small_course_departments')
    op.drop_table('classroom')
    op.drop_table('small_course')
    op.drop_table('big_course')
    op.drop_table('behavior')
    # ### end Alembic commands ###
